
# This is a basic workflow to help you get started with the Run C/C++test action for Make-based project.
name: my first workfolw

on:
  # Triggers the workflow on push or pull request events but only for the master (main) branch.
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  Run-on-wsl:
    name: Polyspace Bug Finder Analysis

    # Specifies the type of runner that the job will run on.
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
    
    - name: checkout
      uses: actions/checkout@master

    # Checks out your repository under $GITHUB_WORKSPACE, so that your job can access it.
    - name: Polyspace Bug Finder analysis
      run: |
        dir
        pwd 
        echo 'hello github on self hosted machine'
        polyspace-bug-finder-server -sources first_analysis.c -misra3 all -checkers all
        
    - name: Gen SARIF from local result
      if: always()
      run: polyspace-results-export -format json-sarif -results-dir . -output-name firstresult.json
        
    - name: Upload results (SARIF)
      if: always()
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: firstresult.json
     
      
  Run-on-github:
    name: echo on github hosted machine

    # Specifies the type of runner that the job will run on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:

    # Checks out your repository under $GITHUB_WORKSPACE, so that your job can access it.
    - name: echo date 
      run: date
